name: NEW webscraper
# needs DESCRIPTION file

# set timer when script will run 
on:
  schedule:
  - cron: 0 15 * * *
  
# run script on push
#on:
#  push:
#    branches: 
#      - main

jobs:
  RScript:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rvest
            any::dplyr
            any::tidyr
      - run: Rscript scraper.R
      
 # Add new file in data folder and push
      - name: commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add *.csv
          git commit -am "Scheduled Github Action on $(date)"
          git push origin main
